swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Fetch all transactions of one bank account API
      description: Retrieve the transaction data according to the bank account and the user
      responses:
        '200':
          description: Transactions data retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Id
        '404':
          description: Transactions not found
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      security:
      - Bearer: []
      tags:
        - Transaction Module
      summary: Fecth specific data for one tranction
      description: Retrieve one transaction data according to the transaction's Id
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}/category:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction category
      description: Update transaction category
      parameters:
        - in: path
          name: transactionId
          required: true
          schema:
          type: integer
          format: int64
        -   in: body
            name: categoryId
            required: true
            schema:
              $ref: '#/definitions/Category'
      responses:
        '200':
          description: Transaction modified successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Id
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/{transactionId}/note:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction note
      description: Update transaction note
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
          format: int64
        -   in: body
            name: categoryId
            required: true
            schema:
              $ref: '#/definitions/Note'
      responses:
        '200':
          description: Transaction fetched successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Id
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: integer
      balance:
        type: integer
      type:
        type: integer
        description: transaction type id
      category:
        type: integer
        description: transaction category id
      note:
        type: string
      moreInfos:
        type: string
  TransactionsResponse:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: integer
      balance:
        type: integer
      type:
        type: integer
        description: transaction type id
      category:
        type: integer
        description: transaction category id
      note:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Category:
    properties:
        category:
          type: integer
  Note:
    type: object
    properties:
        note:
          type: string